spring.application.name=demo
# MySQL database connection
# MySQL is running in Docker and is exposed on localhost:3306
spring.datasource.url=jdbc:mysql://localhost:3306/on_demand_delivery_db

# Application-level MySQL account created by docker-compose.yml
spring.datasource.username=delivery_user
spring.datasource.password=delivery_password

# The MySQL driver is usually detected automatically.
# This line is optional but makes the driver explicit.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver